### ISSUE TITLE
changes to `loadtxt` behavior in numpy v1.23.0

### ISSUE THREAD

**Issue by pranabdas** [pranabdas/suvtools#1]
Currently python tests are failing because of changes to `load_txt` behavior in numpy v1.23.0

```
/home/src/load.py:73: UserWarning: Input line 772 contained no data and will not be counted towards `max_rows=6517`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  return np.loadtxt(filename, comments='#', skiprows=line_start-1, \
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.10/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/lib/python3.10/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/usr/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/tests.py", line 19, in <module>
    data = load("dataset/sample_data.txt", 12)
  File "/home/src/load.py", line 73, in load
    return np.loadtxt(filename, comments='#', skiprows=line_start-1, \
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 1301, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 979, in _read
    arr = _load_from_filelike(
ValueError: the number of columns changed from 11 to 10 at row 6502; use `usecols` to select a subset and avoid this error
```

**Comment by pranabdas** [comment]
Empty lines including comment lines no longer counts towards `max_rows` in `numpy.loadtxt`.

https://numpy.org/doc/stable/release/1.23.0-notes.html#np-loadtxt-has-recieved-several-changes

**Comment by pranabdas** [comment]
Fixed in https://github.com/pranabdas/suvtools/commit/4e9ae85816c1e0bd2dd61e35aa56fc285eff5e06
